apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: application-hub
    server: https://kubernetes.default.svc
  project: k3s-dev
  source:
    path: k8s-resources/postgres
    repoURL: https://github.com/willyw0nka/argocd-poc.git
    targetRevision: HEAD
